name: CI

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: npm install
    - name: tsc
      run: npx tsc -b
    - name: lint
      run: npm run lint
      env:
        CI: true
